omarchy-theme-install https://github.com/Gazler/omarchy-solarized-theme
omarchy-theme-install https://github.com/JaxonWright/omarchy-midnight-theme
omarchy-theme-install https://github.com/Swarnim114/omarchy-monochrome-theme
omarchy-theme-install https://github.com/TyRichards/omarchy-space-monkey-theme
omarchy-theme-install https://github.com/bjarneo/omarchy-ash-theme
omarchy-theme-install https://github.com/bjarneo/omarchy-aura-theme
omarchy-theme-install https://github.com/bjarneo/omarchy-futurism-theme
omarchy-theme-install https://github.com/bjarneo/omarchy-nes-theme
omarchy-theme-install https://github.com/bjarneo/omarchy-snow-theme
omarchy-theme-install https://github.com/catlee/omarchy-dracula-theme
omarchy-theme-install https://github.com/dfrico/omarchy-solarized-light-theme
omarchy-theme-install https://github.com/euandeas/omarchy-flexoki-dark-theme
omarchy-theme-install https://github.com/euandeas/omarchy-flexoki-light-theme
omarchy-theme-install https://github.com/guilhermetk/omarchy-all-hallows-eve-theme
omarchy-theme-install https://github.com/guilhermetk/omarchy-rose-pine-dark
omarchy-theme-install https://github.com/hipsterusername/omarchy-blueridge-dark-theme
omarchy-theme-install https://github.com/hipsterusername/omarchy-milkmatcha-light-theme
omarchy-theme-install https://github.com/hipsterusername/omarchy-waveform-dark-theme
omarchy-theme-install https://github.com/motorsss/omarchy-solarizedosaka-theme
omarchy-theme-install https://github.com/omacom-io/omarchy-synthwave84-theme
omarchy-theme-install https://github.com/rondilley/omarchy-retropc-theme
omarchy-theme-install https://github.com/steve-lohmeyer/omarchy-mars-theme
omarchy-theme-install https://github.com/tahayvr/omarchy-gold-rush-theme
