alias ll='ls -l'
alias ql='qlmanage -p "$@" 1>/dev/null 2>&1' # Quick Look
alias vi=nvim

export EDITOR="nvim -c 'set tw=0'"
export FZF_DEFAULT_COMMAND='ag -g ""'
export HISTCONTROL=ignoreboth:erasedups
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export PATH="/usr/local/opt/llvm/bin:$PATH"
export PYTHONSTARTUP=~/.pythonrc
export TERM=screen-256color
export VIMCONFIG=/Users/andresarayarojas/.config/nvim

set -o vi

[ -z "$ZSH_NAME" ] && [ -f ~/.fzf.bash ] && source ~/.fzf.bash
