alias ll='ls -l'
alias ql='qlmanage -p "$@" 1>/dev/null 2>&1' # Quick Look
alias vi=nvim

export EDITOR="nvim -c 'set tw=0'"
export HISTCONTROL=ignoreboth:erasedups
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export TERM=screen-256color
export VIMCONFIG=/Users/andresarayarojas/.config/nvim

set -o vi

[ -z "$ZSH_NAME" ] && [ -f ~/.fzf.bash ] && source ~/.fzf.bash
eval "$(pyenv init -)"

export PYENV_ROOT=`pyenv root`

# Created by `pipx` on 2021-09-05 17:02:25
export PATH="$PATH:/Users/andresarayarojas/.local/bin"

autoload -U bashcompinit && bashcompinit
autoload -U compinit && compinit
eval "$(register-python-argcomplete pipx)"
