alias ls='exa'
alias ll='ls -l'
alias ql='qlmanage -p "$@" 1>/dev/null 2>&1'
alias ctags="`brew --prefix`/bin/ctags"

type nvim >/dev/null 2>&1 && alias vi=nvim || alias vi=vim
export HISTCONTROL=ignoreboth:erasedups
export FONTCONFIG_PATH=/opt/X11/lib/X11/fontconfig
export EDITOR="nvim -c 'set tw=0'"
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export TERM=screen-256color
export PS1='\W $ '
export VIMCONFIG=/Users/andresarayarojas/.config/nvim
export PYTHONSTARTUP=~/.pythonrc

set -o vi
bind -m vi-insert "\C-l":clear-screen

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
