alias vi=nvim
if which bat 2>&1 >/dev/null; then
  alias cat='bat --style=plain'
fi

set -o vi
bind -m vi-command 'Control-l: clear-screen'
bind -m vi-insert 'Control-l: clear-screen'

export MANPAGER='nvim +Man!'
export VCPKG_ROOT=$HOME/.local/share/vcpkg

# Set up fzf key bindings and fuzzy completion
eval "$(fzf --bash)"

